apiVersion: v1
kind: Pod
metadata:
  name: mypod-b
  labels:
    app: my-app
  namespace: prod
spec:
  containers:
  - name: nginx-container
    image: nginx
    ports:
    - containerPort: 80
  - name: tomcat-container
    image: tomcat
    ports:
    - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata: 
  name: my-svc
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80